services:
  room-alert:
    build:
      context: .
    container_name: toyoko-inn-room-alert
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Taipei
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
